package com.greendao.entity;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "CUPBOARD".
 */
@Entity
public class Cupboard {

    @Id
    private Long id;
    private String code;
    private String name;
    private String location;
    private String storeroomName;
    private String storeroomCode;
    private String remark;

    @Generated
    public Cupboard() {
    }

    public Cupboard(Long id) {
        this.id = id;
    }

    @Generated
    public Cupboard(Long id, String code, String name, String location, String storeroomName, String storeroomCode, String remark) {
        this.id = id;
        this.code = code;
        this.name = name;
        this.location = location;
        this.storeroomName = storeroomName;
        this.storeroomCode = storeroomCode;
        this.remark = remark;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public String getStoreroomName() {
        return storeroomName;
    }

    public void setStoreroomName(String storeroomName) {
        this.storeroomName = storeroomName;
    }

    public String getStoreroomCode() {
        return storeroomCode;
    }

    public void setStoreroomCode(String storeroomCode) {
        this.storeroomCode = storeroomCode;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

}
