package com.greendao.entity;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "PROTECT".
 */
@Entity
public class Protect {

    @Id
    private Long id;
    private String StoreroomCode;
    private String StoreroomName;
    private String ProtectType;
    private String ProtectTime;
    private String ProtectResult;
    private String OperUser;

    @Generated
    public Protect() {
    }

    public Protect(Long id) {
        this.id = id;
    }

    @Generated
    public Protect(Long id, String StoreroomCode, String StoreroomName, String ProtectType, String ProtectTime, String ProtectResult, String OperUser) {
        this.id = id;
        this.StoreroomCode = StoreroomCode;
        this.StoreroomName = StoreroomName;
        this.ProtectType = ProtectType;
        this.ProtectTime = ProtectTime;
        this.ProtectResult = ProtectResult;
        this.OperUser = OperUser;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getStoreroomCode() {
        return StoreroomCode;
    }

    public void setStoreroomCode(String StoreroomCode) {
        this.StoreroomCode = StoreroomCode;
    }

    public String getStoreroomName() {
        return StoreroomName;
    }

    public void setStoreroomName(String StoreroomName) {
        this.StoreroomName = StoreroomName;
    }

    public String getProtectType() {
        return ProtectType;
    }

    public void setProtectType(String ProtectType) {
        this.ProtectType = ProtectType;
    }

    public String getProtectTime() {
        return ProtectTime;
    }

    public void setProtectTime(String ProtectTime) {
        this.ProtectTime = ProtectTime;
    }

    public String getProtectResult() {
        return ProtectResult;
    }

    public void setProtectResult(String ProtectResult) {
        this.ProtectResult = ProtectResult;
    }

    public String getOperUser() {
        return OperUser;
    }

    public void setOperUser(String OperUser) {
        this.OperUser = OperUser;
    }

}
